repos:
  - repo: https://github.com/bufbuild/buf
    rev: v1.34.0
    hooks:
      - id: buf-lint
      - id: buf-breaking
        args: ["--against", "buf.build/krelinga/proto"]
        verbose: true
          # log_file: /tmp/buf_breaking.log
      - id: buf-dep-update
      - id: buf-dep-prune
