repos:
  - repo: https://github.com/bufbuild/buf
    rev: v1.34.0
    hooks:
      - id: buf-lint
      - id: buf-breaking
        args: ["--against", ".git"]
      - id: buf-dep-update
      - id: buf-dep-prune
